### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Kyrt-del** [Kyrt-del/Grp-20-Healthcare-Management#13]
Login Auth

**Comment by Hardik3172** [comment]
import React, { useEffect, useState } from "react";
import firebaseConfig from "../config.js";

export const AuthContext = React.createContext();

export const AuthProvider = ({ children }) => {
  const [loading, setLoading] = useState(true);
  const [currentUser, setCurrentUser] = useState(null);
  useEffect(() => {
    firebaseConfig.auth().onAuthStateChanged((user) => {
      setCurrentUser(user);
      setLoading(false);
    });
  }, []);
  if (loading) {
    return <p>Loading...</p>;
  }
  return (
    <AuthContext.Provider value={{ currentUser }}>
      {children}
    </AuthContext.Provider>
  );
};

**Comment by Kyrt-del** [comment]
In the SignIn javascript, changes regarding the redirection to the patient or doctor's page have to be made once those pages are added. 
Authentication issue can be closed.

**Comment by SmitMangukiya** [comment]
done
